# Copyright (c) 2001-2021 by SAP SE, Walldorf, Germany.
# All rights reserved. Confidential and proprietary.

# ansible 2.11
---
  - name: Setup SapMachine Linux ppc64_le Clients
    hosts: SapMachineClients-Linux-ppc64le
    gather_facts: Yes
    pre_tasks:
      - name: 'install python'
        raw: sudo apt-get update && sudo apt-get -qq -y --no-install-recommends install python python3
    vars:
      jenkins_client_name: agent-linux-ppc64le-{{ jenkins_client_index }}
      jenkins_server_url: https://ci.sapmachine.io/computer/{{ jenkins_client_name }}/jenkins-agent.jnlp
      jenkins_client_secret_var: "jenkins_client_secret_{{ jenkins_client_index }}"
      sapmachine_version: "17.0.1"
      sapmachine_tgz: "sapmachine-jre-{{ sapmachine_version }}_linux-ppc64le_bin.tar.gz"
      sapmachine_url: "https://github.com/SAP/SapMachine/releases/download/sapmachine-{{ sapmachine_version }}/{{ sapmachine_tgz }}"

    tasks:

      - name: System details
        debug: msg="{{ item }}"
        with_items:
        - "{{ ansible_distribution }}"
        - "{{ ansible_distribution_version }}"
        - "{{ ansible_distribution_major_version }}"
        tags:
          - system.details

      - name: install apt-transport-https
        apt:
          name: apt-transport-https
          state: latest
          install_recommends: no
        become: yes
        tags:
          - packages.apt-transport-https

      - name: install acl
        apt:
          name: acl
          state: latest
          install_recommends: no
        become: yes
        tags:
          - packages.apt-transport-https

      - name: add docker apt key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
        become: yes
        tags:
          - packages.docker_key

      - name: add docker repository 16.04 Xenial
        apt_repository:
         repo: deb [arch=ppc64el] https://download.docker.com/linux/ubuntu xenial stable
         state: present
        become: yes
        tags:
          - packages.docker_repository_xenial
        when: ansible_distribution_major_version == '16'

      - name: add docker repository 20.04 Focal
        apt_repository:
         repo: deb [arch=ppc64el] https://download.docker.com/linux/ubuntu focal stable
         state: present
        become: yes
        tags:
          - packages.docker_repository_focal
        when: ansible_distribution_major_version == '20'

      # install docker
      - name: install docker-ce
        apt:
          name: docker-ce
          state: latest
          install_recommends: no
        become: yes
        tags:
          - packages.docker-ce

      # create jenkins group used for running the jenkins client
      - name: create jenkins group
        group:
          name: jenkins
          state: present
        become: yes
        tags:
          - groups.create_jenkins

      # create jenkins user used for running the jenkins client
      - name: create jenkins user
        user:
          name: jenkins
          comment: "Jenkins user"
          groups: jenkins, docker
        become: yes
        tags:
          - users.create_jenkins

      # create the jenkins client home directory
      - name: create Jenkins client home directory
        file:
          path: /home/jenkins/client-home
          state: directory
        become: yes
        become_user: jenkins
        tags:
          - jenkins_client.create_home

      # download the jenkins client jar file
      - name: download Jenkins client jar
        get_url:
          url: "http://ci.sapmachine.io/jnlpJars/agent.jar"
          dest: /home/jenkins/client.jar
          force: yes
        become: yes
        become_user: jenkins
        tags:
          - jenkins_client
          - jenkins_client.download_client_jar

      # copy the script file to start the jenkins client
      - name: copy Jenkins client files
        synchronize:
          src: ../ci-client-local/start-client.sh
          dest: /home/jenkins/start-client.sh
        become: yes
        become_user: jenkins
        tags:
          - jenkins_client.copy_files

      # enable Docker IPv6
      - name: install Docker Daemon configuration
        copy:
          src: daemon.json
          dest: /etc/docker/daemon.json
          owner: root
          group: root
          mode: 0644
        become: yes
        tags:
          - docker.config_install

      - name: reload the Docker Daemon configuration
        systemd: state=restarted name=docker
        become: yes
        tags:
          - docker.config_reload

      # stop all running java processes (jenkins client)
      - name: stop all Java processes
        command: killall -9 java
        become: yes
        failed_when: false
        tags:
          - java.kill_all

      # delete old SapMachine
      - name: Delete old SapMachine
        shell: "rm -rf sapmachine-jre*"
        args:
          chdir: /home/jenkins
        become: yes
        become_user: jenkins
        tags:
          - remove.sapmachine

      # download SapMachine 17
      - name: Download SapMachine 17
        shell: "wget {{ sapmachine_url }} && tar -xzf {{ sapmachine_tgz }} && rm {{ sapmachine_tgz }} && mv sapmachine-jre* sapmachine-jre"
        args:
          chdir: /home/jenkins
        become: yes
        become_user: jenkins
        tags:
          - download.sapmachine

      # start the jenkins client
      - name: start Jenkins client
        command: "/home/jenkins/start-client.sh {{ jenkins_server_url }} {{ lookup('vars', jenkins_client_secret_var) }}"
        args:
          chdir: /home/jenkins
        become: yes
        become_user: jenkins
        tags:
          - jenkins_client.start
