name: Parse and Modify CSV Files

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *'  # Optional: Runs daily at midnight

jobs:
  process_csv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: release_stats  # Check out the release_stats branch

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: sudo apt-get install jq

    - name: Configure Git
      run: |
        git config --local user.email "sapmachine@sap.com"
        git config --local user.name "SapMachine Github Actions Bot"

    - name: Run CSV processing
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Fetch CSV files from the stats folder
        files=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/SAP/SapMachine-infrastructure/contents/stats?ref=release_stats" | \
          jq -r '.[] | select(.name | endswith(".csv")) | .path')

        # Create a new branch for changes
        BRANCH_NAME="update-csv-${{ github.run_id }}"
        git checkout -b $BRANCH_NAME

        changes_made=false  # Flag to track if changes were made

        for file in $files; do
          echo "Processing $file"
          
          # Fetch and decode CSV content
          csv_content=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/SAP/SapMachine-infrastructure/contents/$file?ref=release_stats" | \
            jq -r '.content' | base64 --decode)

          # Output original content for debugging
          echo "Original Content:"
          echo "$csv_content"

        
