name: Parse and Modify CSV Files

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *'  # Optional: Runs daily at midnight

jobs:
  process_csv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: sudo apt-get install jq

    - name: Configure Git
      run: |
        git config --local user.email "sapmachine@sap.com"
        git config --local user.name "SapMachine Github Actions Bot"

    - name: Run CSV processing
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Fetch CSV files
        files=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/SAP/SapMachine-Infrastructure/contents/stats?ref=release_stats" | \
          jq -r '.[] | select(.name | endswith(".csv")) | .path')

        # Create a new branch for changes
        BRANCH_NAME="update-csv-${{ github.run_id }}"
        git checkout -b $BRANCH_NAME

        changes_made=false  # Flag to track if changes were made

        for file in $files; do
          echo "Processing $file"
          
          # Fetch and decode CSV content
          csv_content=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/SAP/SapMachine-Infrastructure/contents/$file?ref=release_stats" | \
            jq -r '.content' | base64 --decode)

          # Modify the CSV content
          modified_content=$(echo "$csv_content" | awk -F, '
            BEGIN {OFS=","}
            {
              if ($5 ~ /\.rpm$/) $6 = "Linux";  # Update os_name (6th column) if asset_name (5th column) ends with .rpm
              print
            }')

          # Create the directory structure if it doesn't exist
          mkdir -p "$(dirname "$file")"

          # Check if the modified content differs from the original
          if [[ "$csv_content" != "$modified_content" ]]; then
            changes_made=true  # Set flag if changes are detected
            # Write the modified content back to the original file
            echo "$modified_content" > "$file"
            # Add the modified file to git
            git add "$file"
          fi
        done

        # Commit the changes if any were made
        if [ "$changes_made" = true ]; then
          git commit -m "Update CSV files: set os_name to Linux for RPM files"

          # Create a pull request
          gh pr create --base release_stats --head $BRANCH_NAME --title "Update CSV Files" --body "This PR updates the os_name to Linux for RPM files."
        else
          echo "No changes made; skipping PR creation."
        fi

    - name: Push changes to remote
      run: |
        if [ "$changes_made" = true ]; then
          git push origin $BRANCH_NAME
        fi
