name: Build and Publish SapMachine container images to the SAP GitHub Container Registry
on:
  workflow_dispatch:

jobs:
  publish_images:
    strategy:
        matrix:
          sapMachineVersion: [17, 21, 23]
          gardenLinuxVersion: [1592]   
    uses: ./.github/workflows/publish-container-images.yaml
    with:
      sapMachineVersion: ${{ matrix.sapMachineVersion }}
      gardenLinuxVersion:  ${{ matrix.gardenLinuxVersion }}
